# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - automate-docker-image-builds-with-acr-from-the-pipeline--179500509

variables:
  DatabaseName: benchmarks_test
  DbUser: 83edada839
  DbPassword: d24e1f8180
  DbUrl: postgres://'$(DbUser)':'$(DbPassword)'@localhost:5432/'$(DatabaseName)'

#resources:
#  containers:
#    - container: ubuntu_postgres
#      image: ubuntu/postgres
#      type: docker
#      options: -e POSTGRES_USER='$(DbUser)' -e POSTGRES_PASSWORD='$(DbPassword)' -e POSTGRES_DB='$(DatabaseName)' -p 5432:5432

# the MS-provided ubuntu-20.04 image includes postgres
# full list of includes software:
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
pool:
  vmImage: ubuntu-20.04
#  options: -e POSTGRES_USER='$(DbUser)' -e POSTGRES_PASSWORD='$(DbPassword)' -e POSTGRES_DB='$(DatabaseName)' -p 5432:5432

steps:
  - script: env | sort
    displayName: show env vars
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 3.0"
      addToPath: true
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
  - script: bundle install --deployment --path vendor/bundle
    displayName: bundle install
  - script: yarn install --frozen-lockfile --check-files
    displayName: yarn install
  - task: CmdLine@2
    displayName: prepare test db
    inputs:
      script: DATABASE_URL=$(DATABASE_URL) RAILS_ENV=test bin/bundle exec rake db:schema:load db:seed
  - task: CmdLine@2
    displayName: run test suite
    inputs:
      script: DATABASE_URL=$(DATABASE_URL) MINITEST_REPORTER=JUnitReporter bin/bundle exec rake test:all
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: JUnit
      testRunTitle: Benchmarks ruby rspec test suite with in-browser
      testResultsFiles: "**/TEST-*.xml"
  - task: Docker@2
    displayName: Docker Login to ACR
    inputs:
      command: login
      containerRegistry: "Service Endpoint for WHO IHR Benchmarks Azure Container Registry"
  - task: Docker@2
    displayName: Docker Build and Push to ACR
    inputs:
      command: buildAndPush
      containerRegistry: "Service Endpoint for WHO IHR Benchmarks Azure Container Registry"
      repository: benchmarks
      Dockerfile: config/docker/Dockerfile
      tags:
        - latest