# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - feature/azure-spike

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '= 3.0.2'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'
