# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - build-pipeline-installs-postgres-as-a-workaround--179445541

variables:
  DatabaseName: benchmarks_test
  DbUser: 83edada839
  DbPassword: d24e1f8180
  DbUrl: postgres://'$(DbUser)':'$(DbPassword)'@localhost:5432/'$(DatabaseName)'

resources:
  containers:
    - container: ubuntu_postgres
      image: ubuntu/postgres
      options: -e POSTGRES_USER='$(DbUser)' -e POSTGRES_PASSWORD='$(DbPassword)' -e POSTGRES_DB='$(DatabaseName)' -p 5432:5432

pool:
  vmImage: ubuntu_postgres

container: ubuntu_postgres

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 3.0"
      addToPath: true
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
  - script: bundle install --deployment --path vendor/bundle
    displayName: bundle install
  - script: yarn install --frozen-lockfile --check-files
    displayName: yarn install
  - script: env | sort
    displayName: show env vars
  - task: CmdLine@2
    displayName: prepare test db
    inputs:
      script: DATABASE_URL='$(DbUrl)' bin/bundle exec rake test:prepare
  - task: CmdLine@2
    displayName: run test suite
    inputs:
      script: DATABASE_URL='$(DbUrl)' MINITEST_REPORTER=JUnitReporter bin/bundle exec rake test:all
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: JUnit
      testRunTitle: Benchmarks ruby rspec test suite with in-browser
      testResultsFiles: "**/TEST-*.xml"
