# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - pipeline-access-to-db-now-that-its-private--179445514

variables:
  AzureSubscription: pend-db01
  ServerName: psqldb-who-ihr-benchmarks
  DatabaseName: benchmarks_test
  AdminUser: fyxzCNQUqNrd
  AdminPassword: Lo4YdiJcggrN9TfPagCW2AsMtFbQ8R6N
#  SQLFile: '<Location of SQL file in $(Build.SourcesDirectory)>'

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 3.0"
      addToPath: true
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
  - script: bundle install --deployment --path vendor/bundle
    displayName: bundle install
  - script: yarn install --frozen-lockfile --check-files
    displayName: yarn install
  - script: env | sort
    displayName: show env vars
  - script: DATABASE_URL=$(DATABASE_URL) bin/bundle exec rake test:prepare
    displayName: prepare test db
    inputs:
      azureSubscription: '$(AzureSubscription)' # to make it use the service connection to our private DB
    # TODO: may want to break out the different test types to separate tasks like we do in semaphore.yml
  - script: DATABASE_URL=$(DATABASE_URL) MINITEST_REPORTER=JUnitReporter bin/bundle exec rake test:all
    displayName: run test suite
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: JUnit
      testRunTitle: Benchmarks ruby rspec test suite with in-browser
      testResultsFiles: "**/TEST-*.xml"
