# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - pipeline-create-and-setup--178993699--build

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 3.0"
      addToPath: true
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
  - script: bundle install --deployment --path vendor/bundle
    displayName: bundle install
  - script: yarn install --frozen-lockfile --check-files
    displayName: yarn install
  - script: env | sort
    displayName: show env vars
  - script: DATABASE_URL=$(DATABASE_URL) bin/bundle exec rake test:prepare
    displayName: prepare test db
  - script: DATABASE_URL=$(DATABASE_URL) bin/bundle exec rspec --no-drb -r rspec_junit_formatter --format RspecJunitFormatter -o TEST-rspec.xml
    displayName: run test suite
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: JUnit
      testRunTitle: Benchmarks ruby rspec test suite with in-browser
      testResultsFiles: "**/TEST-*.xml"
